spring: 
  social:
        facebook:
            appId: 543517282525567
            appSecret: a76f88cc34b3df45da6cae064e126bf5

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh



...